args <- commandArgs(trailingOnly=TRUE)
if (length(args) != 5) stop("Usage: Rscript rna_deseq2.R counts.tsv samples.tsv reference test new_output_directory")
if (!requireNamespace("DESeq2",quietly=TRUE)) stop("Install Bioconductor DESeq2")
counts <- as.matrix(read.delim(args[1],row.names=1,check.names=FALSE))
samples <- read.delim(args[2],stringsAsFactors=FALSE)
if (!all(c("sample","condition") %in% names(samples))) stop("Required sample columns: sample, condition")
if (anyDuplicated(samples$sample) || anyDuplicated(colnames(counts)) || anyNA(samples[,c("sample","condition")])) stop("Invalid sample identifiers")
if (!is.numeric(counts) || anyNA(counts) || any(!is.finite(counts)) || any(counts<0) || any(counts!=floor(counts))) stop("Counts must be nonnegative integers")
if (!setequal(samples$sample,colnames(counts))) stop("Count/sample identifiers differ")
samples <- samples[match(colnames(counts),samples$sample),,drop=FALSE]
rownames(samples) <- samples$sample
if (args[3] == args[4] || !all(args[3:4] %in% samples$condition)) stop("Invalid contrast")
if (any(table(samples$condition) < 2)) stop("At least two biological replicates per condition required")
samples$condition <- relevel(factor(samples$condition),ref=args[3])
if (file.exists(args[5])) stop("Choose a new output directory")
dds <- DESeq2::DESeqDataSetFromMatrix(countData=counts,colData=samples,design=~condition)
dds <- DESeq2::DESeq(dds,test="Wald",fitType="parametric",betaPrior=FALSE,minReplicatesForReplace=Inf)
result <- DESeq2::results(dds,contrast=c("condition",args[4],args[3]),lfcThreshold=0,
                         cooksCutoff=FALSE,independentFiltering=FALSE,pAdjustMethod="BH")
dir.create(args[5],recursive=TRUE)
write.table(as.data.frame(result),file.path(args[5],"differential_expression.tsv"),sep="\t",quote=FALSE,col.names=NA)
write.table(DESeq2::counts(dds,normalized=TRUE),file.path(args[5],"normalized_counts.tsv"),sep="\t",quote=FALSE,col.names=NA)
saveRDS(dds,file.path(args[5],"DESeq2_fit.rds"))
capture.output(sessionInfo(),file=file.path(args[5],"sessionInfo.txt"))
