---
title: "Part 3: IF Puncta Colocalization - Analysis of ImageJ Measurement Output"
author: "Alec McIntosh"
date: '2023-06-14'
output: html_document
---

```{r setup functions and packages, include=FALSE}
library(DescTools); library(dplyr); library(stringi); library(stringr); library(filesstrings)
library(magrittr); library(ggplot2); library(gridExtra); library(imputeTS)
library(grid); library(car); library(utile.visuals); library(reshape2); library(hfunk)

#Functions
Read.in.Files.Signal <- function(file.list, Channel){
  print(length(file.list))
  
  for (i in 1:length(file.list)){
    
    print(i)
    tmp <- read.delim(file = file.list[i], header = TRUE, sep = '\t', stringsAsFactors = FALSE, na.strings = "")
    #Get Name
    name <- unlist(str_split(string = file.list[i], pattern = "/"))
    name <- name[length(name)]
    name <- gsub(x = name, pattern = ".txt", replacement = "")
    name <- gsub(x = name, pattern = "C1-", replacement = "")
    name <- gsub(x = name, pattern = "C2-", replacement = "")
    tmp$Label <- name
    if(nrow(tmp) > 1){
      index <- max(tmp$Mean)
      tmp <- tmp[index,]
    }
    if (i == 1){summary <- tmp} else{summary <- rbind(summary, tmp)}
    
  }
  
  
  if(Channel == "Ch00"){
  summary <- summary %>% dplyr::select(Label, Area, Mean)
  Classes <- c("char","num","num")
  colnames(summary) <- c("FileName","Total_Area","Mean_DAPI_Signal")
  summary <- changeClass(summary, new = Classes)
  }
  
  if(Channel == "Ch01"){
    summary <- summary %>% dplyr::select(Label, Area, XM, YM)
    Classes <- c("char","num","num","num")
    colnames(summary) <- c("FileName","Ch01_Thresh_Area","Ch01_XM", "Ch01_YM")
    summary <- changeClass(summary, new = Classes)
  }
  
  if(Channel == "Ch02"){
    summary <- summary %>% dplyr::select(Label, Area, XM, YM)
    Classes <- c("char","num","num","num")
    colnames(summary) <- c("FileName","Ch02_Thresh_Area","Ch02_XM", "Ch02_YM")
    summary <- changeClass(summary, new = Classes)
  }
  
  if(Channel == "Ch12"){
    summary <- summary %>% dplyr::select(Label, Area)
    Classes <- c("char","num")
    colnames(summary) <- c("FileName","Common_Area")
    summary <- changeClass(summary, new = Classes)
  }
  
  return(summary)
  
}


 circle_intersection <- function(x1, y1, r1, x2, y2, r2){
  #rr1 <- r1 * r1
  #rr2 <- r2 * r2
  d <- sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1))
  
  if (d > r2 + r1){return(0)} else{return(1)} # Cirlcs do not overlap
  #else if (d <= abs(r1 - r2) && r1 >= r2){ # Circle2 is completely inside circle1  
    #return(pi*rr2)
  #} else if (d <= abs(r1 - r2) && r1 < r2){ # Circle1 is completely inside circle2
   # return(pi*rr1)
  #} else { # Circles partially overlap
  #  phi <- (acos((rr1 + (d * d) - rr2) / (2 * r1 * d))) * 2
  #  theta <- (acos((rr2 + (d * d) - rr1) / (2 * r2 * d))) * 2
   # area2 <- 0.5 * theta * rr2 - 0.5 * rr2 * sin(theta)
   # area1 <- 0.5 * phi * rr1 - 0.5 * rr1 * sin(phi)
   # return(area1 + area2)
}




colourise <- function(text, fg = "black", bg = NULL) {
  term <- Sys.getenv()["TERM"]
  colour_terms <- c("xterm-color","xterm-256color", "screen", "screen-256color")

  if(rcmd_running() || !any(term %in% colour_terms, na.rm = TRUE)) {
    return(text)
  }

  col_escape <- function(col) {
    paste0("\033[", col, "m")
  }

  col <- .fg_colours[tolower(fg)]
  if (!is.null(bg)) {
    col <- paste0(col, .bg_colours[tolower(bg)], sep = ";")
  }

  init <- col_escape(col)
  reset <- col_escape("0")
  paste0(init, text, reset)
}

.fg_colours <- c(
  "black" = "0;30",
  "blue" = "0;34",
  "green" = "0;32",
  "cyan" = "0;36",
  "red" = "0;31",
  "purple" = "0;35",
  "brown" = "0;33",
  "light gray" = "0;37",
  "dark gray" = "1;30",
  "light blue" = "1;34",
  "light green" = "1;32",
  "light cyan" = "1;36",
  "light red" = "1;31",
  "light purple" = "1;35",
  "yellow" = "1;33",
  "white" = "1;37"
)

.bg_colours <- c(
  "black" = "40",
  "red" = "41",
  "green" = "42",
  "brown" = "43",
  "blue" = "44",
  "purple" = "45",
  "cyan" = "46",
  "light gray" = "47"
)

rcmd_running <- function() {
  nchar(Sys.getenv('R_TESTS')) != 0
}

```


```{r Parsing ImageJ output files to compare nuclei puncta overlap (TWO CHANNELS ONLY)}
References <- c("Ch01","Ch02")
Dir = "/Users/..." # File path to base folder containing ImageJ output analysis
folders = c("...","...") # Names of folders within said directory containing ImageJ output analysis



for (j in folders){

x = j 
Input2 = paste(Dir,x,"Combined_Images1", sep = "/")
Dirs = list.dirs(path = Input2, full.names = TRUE)
Dirs = grep(Dirs, pattern = "Channel|Common", value = TRUE)
Ch01 <- list.files(path = intersect(grep(Dirs, pattern = "Channel1", value = TRUE), grep(Dirs, pattern = "Measurements", value = TRUE)), pattern = ".txt", full.names = TRUE)
Ch02 <- list.files(path = intersect(grep(Dirs, pattern = "Channel2", value = TRUE), grep(Dirs, pattern = "Measurements", value = TRUE)), pattern = ".txt", full.names = TRUE)

# Parse through Channel 1

for (i in Ch01){

  y = i
  index <- gsub(y, pattern = "Channel1", replacement = "Channel2")
  item <- which(index %in% Ch02)


  if (length(item) > 0){

    z = Ch02[item]
    tmp1 <- read.delim(y, header = TRUE, sep = '\t', stringsAsFactors = FALSE)
    tmp2 <- read.delim(z, header = TRUE, sep = '\t', stringsAsFactors = FALSE)

    if (nrow(tmp1) > 0 & nrow(tmp2) > 0){

      # Channel 1 Overlaps!!!
      tmp1$Overlap = 0
      for (t1 in 1:nrow(tmp1)){
        A = tmp1[t1,"XM"]
        B = tmp1[t1,"YM"]
        C = sqrt(tmp1[t1,"Area"]/pi)
        cat(colourise(t1, "red"), "\n")

        for (t2 in 1:nrow(tmp2)){

          a = tmp2[t2,"XM"]
          b = tmp2[t2,"YM"]
          c = sqrt(tmp2[t2,"Area"]/pi)
          #cat(colourise(t2, "light green"), "\n")
          test <- circle_intersection(x1 = A, y1 = B, r1 = C, x2 = a, y2 = b, r2 = c)

          if (test == 1){
            tmp1[t1,"Overlap"] = 1
            print("Overlap Found")
            break
          }
        } # End of T2 Loop
      } # End of T1 Loop

      write.table(file = y, x = tmp1, sep = '\t', row.names = FALSE, col.names = TRUE)
} # Not enough particles to compare
  } # No matching Nuclei
}

      # Channel 2 Overlaps!!!
for (i in Ch02){
  
  y = i
  index <- gsub(y, pattern = "Channel2", replacement = "Channel1")
  item <- which(index %in% Ch01)
  
  
  if (length(item) > 0){
    
    z = Ch01[item]
    tmp1 <- read.delim(y, header = TRUE, sep = '\t', stringsAsFactors = FALSE)
    tmp2 <- read.delim(z, header = TRUE, sep = '\t', stringsAsFactors = FALSE)
    
    if (nrow(tmp1) > 0 & nrow(tmp2) > 0){
      
      # Channel 1 Overlaps!!!
      tmp1$Overlap = 0
      for (t1 in 1:nrow(tmp1)){
        A = tmp1[t1,"XM"]
        B = tmp1[t1,"YM"]
        C = sqrt(tmp1[t1,"Area"]/pi)
        cat(colourise(t1, "green"), "\n")
        
        for (t2 in 1:nrow(tmp2)){
          
          a = tmp2[t2,"XM"]
          b = tmp2[t2,"YM"]
          c = sqrt(tmp2[t2,"Area"]/pi)
          #cat(colourise(t2, "light green"), "\n")
          test <- circle_intersection(x1 = A, y1 = B, r1 = C, x2 = a, y2 = b, r2 = c)
          
          if (test == 1){
            tmp1[t1,"Overlap"] = 1
            print("Overlap Found")
            break
          }
        } # End of T2 Loop
      } # End of T1 Loop
      
      write.table(file = y, x = tmp1, sep = '\t', row.names = FALSE, col.names = TRUE)
    } # Not enough particles to compare
  } # No matching Nuclei
}       
      # tmp2$Overlap = 0
      # for (t2 in 1:nrow(tmp2)){
      #   a = tmp2[t2,"XM"]
      #   b = tmp2[t2,"YM"]
      #   c = sqrt(tmp2[t2,"Area"]/pi)
      #   cat(colourise(t2, "cyan"), "\n")
      #   
      #   
      #   for (t1 in 1:nrow(tmp1)){
      #     A = tmp1[t1,"XM"]
      #     B = tmp1[t1,"YM"]
      #     C = sqrt(tmp1[t1,"Area"]/pi)
      #     #cat(colourise(t1, "red"), "\n")
      #     
      #     test <- circle_intersection(x1 = a, y1 = b, r1 = c, x2 = A, y2 = B, r2 = C)
      #     
      #     if (test == 1){
      #       tmp2[t2,"Overlap"] = 1
      #       print("Overlap Found")
      #       break
      #     }
      #   } # End of T2 Loop
      # } # End of T1 Loop
      # 
      # write.table(file = z, x = tmp2, sep = '\t', row.names = FALSE, col.names = TRUE)
      
    
cat(colourise(text = j, fg = "light purple"), "\n")
}
print("DONE")


```





```{r Outputting Final table and calculating puncta overlap percentages for each nuclei}
References <- c("Ch01","Ch02")
Dir = "/Users/..." # File path to base folder containing ImageJ output analysis
folders = c("...","...") # Names of folders within said directory containing ImageJ output analysis


for (j in folders){
  
x = j 
Input2 = paste(Dir,x,"Combined_Images1", sep = "/")
Dirs = list.dirs(path = Input2, full.names = TRUE)
Dirs = grep(Dirs, pattern = "Channel|Common", value = TRUE)
Ch01 <- list.files(path = intersect(grep(Dirs, pattern = "Channel1", value = TRUE), grep(Dirs, pattern = "Measurements", value = TRUE)), pattern = ".txt", full.names = TRUE)
Ch02 <- list.files(path = intersect(grep(Dirs, pattern = "Channel2", value = TRUE), grep(Dirs, pattern = "Measurements", value = TRUE)), pattern = ".txt", full.names = TRUE)


for (i in References){
  tmp1 <- NULL
  tmp <- get(i)
  
  for (k in 1:length(tmp)){
    cat(colourise(k, "blue"), "\n")
    table <- read.delim(file = tmp[k], header = TRUE, sep = '\t', stringsAsFactors = FALSE, na.strings = "")
    if (nrow(table) > 1){
    #Get Name
    name <- unlist(str_split(string = tmp[k], pattern = "/"))
    name <- name[length(name)]
    name <- gsub(x = name, pattern = ".txt", replacement = "")
    name <- gsub(x = name, pattern = "C1-", replacement = "")
    name <- gsub(x = name, pattern = "C2-", replacement = "")
    table$Label <- name
    
      if(i == "Ch01"){
    table <- table %>% dplyr::select(Label, Overlap)
    index <- which(table$Overlap == 1)
    table$Overlap <- length(index)/nrow(table)
    table <- table %>% distinct()
    colnames(table) <- c("FileName","Ch01_Overlap_Ch02")
    
    
  }
  
    if(i == "Ch02"){
    table <- table %>% dplyr::select(Label, Overlap)
    index <- which(table$Overlap == 1)
    table$Overlap <- length(index)/nrow(table)
    table <- table %>% distinct()
    colnames(table) <- c("FileName", "Ch02_Overlap_Ch01")
    
    }
    
    if(k == 1){tmp1 <- table} else{tmp1 <- rbind(tmp1,table)}
    } else{}
  }
  
  assign(value = tmp1, x = i)

}

Overlap.Summary <- dplyr::full_join(x = Ch01, y = Ch02, by = "FileName")
write.table(x = Overlap.Summary, file = paste(Input2, "/Particle_Overlap_Percentages.txt", sep = ""), row.names = FALSE, sep = '\t')

}
print("DONE")



```




